#This file stores configuration options for Iris, such as the currently active shaderpack
<<<<<<< HEAD
#Sat May 30 17:42:50 BST 2026
=======
#Sat May 23 21:02:05 BST 2026
>>>>>>> refs/remotes/origin/main
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=12
shaderPack=ComplementaryUnbound_r5.8.1 + EuphoriaPatches_1.9.2
