#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue May 19 11:03:33 BST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=12
shaderPack=iterationT 3.2.0.zip
