#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun May 17 19:26:31 BST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=12
shaderPack=ComplementaryUnbound_r5.8 + EuphoriaPatches_1.9.0
